// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: game.proto

package game_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgAccountLoginGameReq_ProtoId int32

const (
	MsgAccountLoginGameReq_None MsgAccountLoginGameReq_ProtoId = 0
	MsgAccountLoginGameReq_Id   MsgAccountLoginGameReq_ProtoId = 1
)

// Enum value maps for MsgAccountLoginGameReq_ProtoId.
var (
	MsgAccountLoginGameReq_ProtoId_name = map[int32]string{
		0: "None",
		1: "Id",
	}
	MsgAccountLoginGameReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   1,
	}
)

func (x MsgAccountLoginGameReq_ProtoId) Enum() *MsgAccountLoginGameReq_ProtoId {
	p := new(MsgAccountLoginGameReq_ProtoId)
	*p = x
	return p
}

func (x MsgAccountLoginGameReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgAccountLoginGameReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[0].Descriptor()
}

func (MsgAccountLoginGameReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[0]
}

func (x MsgAccountLoginGameReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgAccountLoginGameReq_ProtoId.Descriptor instead.
func (MsgAccountLoginGameReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0, 0}
}

type MsgAccountLoginGameAck_ProtoId int32

const (
	MsgAccountLoginGameAck_None MsgAccountLoginGameAck_ProtoId = 0
	MsgAccountLoginGameAck_Id   MsgAccountLoginGameAck_ProtoId = 2
)

// Enum value maps for MsgAccountLoginGameAck_ProtoId.
var (
	MsgAccountLoginGameAck_ProtoId_name = map[int32]string{
		0: "None",
		2: "Id",
	}
	MsgAccountLoginGameAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   2,
	}
)

func (x MsgAccountLoginGameAck_ProtoId) Enum() *MsgAccountLoginGameAck_ProtoId {
	p := new(MsgAccountLoginGameAck_ProtoId)
	*p = x
	return p
}

func (x MsgAccountLoginGameAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgAccountLoginGameAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[1].Descriptor()
}

func (MsgAccountLoginGameAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[1]
}

func (x MsgAccountLoginGameAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgAccountLoginGameAck_ProtoId.Descriptor instead.
func (MsgAccountLoginGameAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0}
}

type MsgTimeSyncReq_ProtoId int32

const (
	MsgTimeSyncReq_None MsgTimeSyncReq_ProtoId = 0
	MsgTimeSyncReq_Id   MsgTimeSyncReq_ProtoId = 10
)

// Enum value maps for MsgTimeSyncReq_ProtoId.
var (
	MsgTimeSyncReq_ProtoId_name = map[int32]string{
		0:  "None",
		10: "Id",
	}
	MsgTimeSyncReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   10,
	}
)

func (x MsgTimeSyncReq_ProtoId) Enum() *MsgTimeSyncReq_ProtoId {
	p := new(MsgTimeSyncReq_ProtoId)
	*p = x
	return p
}

func (x MsgTimeSyncReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgTimeSyncReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[2].Descriptor()
}

func (MsgTimeSyncReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[2]
}

func (x MsgTimeSyncReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgTimeSyncReq_ProtoId.Descriptor instead.
func (MsgTimeSyncReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2, 0}
}

type MsgTimeSyncAck_ProtoId int32

const (
	MsgTimeSyncAck_None MsgTimeSyncAck_ProtoId = 0
	MsgTimeSyncAck_Id   MsgTimeSyncAck_ProtoId = 11
)

// Enum value maps for MsgTimeSyncAck_ProtoId.
var (
	MsgTimeSyncAck_ProtoId_name = map[int32]string{
		0:  "None",
		11: "Id",
	}
	MsgTimeSyncAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   11,
	}
)

func (x MsgTimeSyncAck_ProtoId) Enum() *MsgTimeSyncAck_ProtoId {
	p := new(MsgTimeSyncAck_ProtoId)
	*p = x
	return p
}

func (x MsgTimeSyncAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgTimeSyncAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[3].Descriptor()
}

func (MsgTimeSyncAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[3]
}

func (x MsgTimeSyncAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgTimeSyncAck_ProtoId.Descriptor instead.
func (MsgTimeSyncAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3, 0}
}

type MsgPlayerEnterGameReq_ProtoId int32

const (
	MsgPlayerEnterGameReq_None MsgPlayerEnterGameReq_ProtoId = 0
	MsgPlayerEnterGameReq_Id   MsgPlayerEnterGameReq_ProtoId = 100
)

// Enum value maps for MsgPlayerEnterGameReq_ProtoId.
var (
	MsgPlayerEnterGameReq_ProtoId_name = map[int32]string{
		0:   "None",
		100: "Id",
	}
	MsgPlayerEnterGameReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   100,
	}
)

func (x MsgPlayerEnterGameReq_ProtoId) Enum() *MsgPlayerEnterGameReq_ProtoId {
	p := new(MsgPlayerEnterGameReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerEnterGameReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerEnterGameReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[4].Descriptor()
}

func (MsgPlayerEnterGameReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[4]
}

func (x MsgPlayerEnterGameReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerEnterGameReq_ProtoId.Descriptor instead.
func (MsgPlayerEnterGameReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0}
}

type MsgPlayerEnterGameAck_ProtoId int32

const (
	MsgPlayerEnterGameAck_None MsgPlayerEnterGameAck_ProtoId = 0
	MsgPlayerEnterGameAck_Id   MsgPlayerEnterGameAck_ProtoId = 101
)

// Enum value maps for MsgPlayerEnterGameAck_ProtoId.
var (
	MsgPlayerEnterGameAck_ProtoId_name = map[int32]string{
		0:   "None",
		101: "Id",
	}
	MsgPlayerEnterGameAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   101,
	}
)

func (x MsgPlayerEnterGameAck_ProtoId) Enum() *MsgPlayerEnterGameAck_ProtoId {
	p := new(MsgPlayerEnterGameAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerEnterGameAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerEnterGameAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[5].Descriptor()
}

func (MsgPlayerEnterGameAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[5]
}

func (x MsgPlayerEnterGameAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerEnterGameAck_ProtoId.Descriptor instead.
func (MsgPlayerEnterGameAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5, 0}
}

type MsgPlayerEnterGameFinishNtf_ProtoId int32

const (
	MsgPlayerEnterGameFinishNtf_None MsgPlayerEnterGameFinishNtf_ProtoId = 0
	MsgPlayerEnterGameFinishNtf_Id   MsgPlayerEnterGameFinishNtf_ProtoId = 102
)

// Enum value maps for MsgPlayerEnterGameFinishNtf_ProtoId.
var (
	MsgPlayerEnterGameFinishNtf_ProtoId_name = map[int32]string{
		0:   "None",
		102: "Id",
	}
	MsgPlayerEnterGameFinishNtf_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   102,
	}
)

func (x MsgPlayerEnterGameFinishNtf_ProtoId) Enum() *MsgPlayerEnterGameFinishNtf_ProtoId {
	p := new(MsgPlayerEnterGameFinishNtf_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerEnterGameFinishNtf_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerEnterGameFinishNtf_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[6].Descriptor()
}

func (MsgPlayerEnterGameFinishNtf_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[6]
}

func (x MsgPlayerEnterGameFinishNtf_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerEnterGameFinishNtf_ProtoId.Descriptor instead.
func (MsgPlayerEnterGameFinishNtf_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6, 0}
}

type MsgPlayerEnterGameSync_ProtoId int32

const (
	MsgPlayerEnterGameSync_None MsgPlayerEnterGameSync_ProtoId = 0
	MsgPlayerEnterGameSync_Id   MsgPlayerEnterGameSync_ProtoId = 103
)

// Enum value maps for MsgPlayerEnterGameSync_ProtoId.
var (
	MsgPlayerEnterGameSync_ProtoId_name = map[int32]string{
		0:   "None",
		103: "Id",
	}
	MsgPlayerEnterGameSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   103,
	}
)

func (x MsgPlayerEnterGameSync_ProtoId) Enum() *MsgPlayerEnterGameSync_ProtoId {
	p := new(MsgPlayerEnterGameSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerEnterGameSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerEnterGameSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[7].Descriptor()
}

func (MsgPlayerEnterGameSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[7]
}

func (x MsgPlayerEnterGameSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerEnterGameSync_ProtoId.Descriptor instead.
func (MsgPlayerEnterGameSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7, 0}
}

type MsgPlayerExitGameReq_ProtoId int32

const (
	MsgPlayerExitGameReq_None MsgPlayerExitGameReq_ProtoId = 0
	MsgPlayerExitGameReq_Id   MsgPlayerExitGameReq_ProtoId = 110
)

// Enum value maps for MsgPlayerExitGameReq_ProtoId.
var (
	MsgPlayerExitGameReq_ProtoId_name = map[int32]string{
		0:   "None",
		110: "Id",
	}
	MsgPlayerExitGameReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   110,
	}
)

func (x MsgPlayerExitGameReq_ProtoId) Enum() *MsgPlayerExitGameReq_ProtoId {
	p := new(MsgPlayerExitGameReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerExitGameReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerExitGameReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[8].Descriptor()
}

func (MsgPlayerExitGameReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[8]
}

func (x MsgPlayerExitGameReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerExitGameReq_ProtoId.Descriptor instead.
func (MsgPlayerExitGameReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8, 0}
}

type MsgPlayerExitGameAck_ProtoId int32

const (
	MsgPlayerExitGameAck_None MsgPlayerExitGameAck_ProtoId = 0
	MsgPlayerExitGameAck_Id   MsgPlayerExitGameAck_ProtoId = 111
)

// Enum value maps for MsgPlayerExitGameAck_ProtoId.
var (
	MsgPlayerExitGameAck_ProtoId_name = map[int32]string{
		0:   "None",
		111: "Id",
	}
	MsgPlayerExitGameAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   111,
	}
)

func (x MsgPlayerExitGameAck_ProtoId) Enum() *MsgPlayerExitGameAck_ProtoId {
	p := new(MsgPlayerExitGameAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerExitGameAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerExitGameAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[9].Descriptor()
}

func (MsgPlayerExitGameAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[9]
}

func (x MsgPlayerExitGameAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerExitGameAck_ProtoId.Descriptor instead.
func (MsgPlayerExitGameAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9, 0}
}

type MsgPlayerExitGameSync_ProtoId int32

const (
	MsgPlayerExitGameSync_None MsgPlayerExitGameSync_ProtoId = 0
	MsgPlayerExitGameSync_Id   MsgPlayerExitGameSync_ProtoId = 112
)

// Enum value maps for MsgPlayerExitGameSync_ProtoId.
var (
	MsgPlayerExitGameSync_ProtoId_name = map[int32]string{
		0:   "None",
		112: "Id",
	}
	MsgPlayerExitGameSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   112,
	}
)

func (x MsgPlayerExitGameSync_ProtoId) Enum() *MsgPlayerExitGameSync_ProtoId {
	p := new(MsgPlayerExitGameSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerExitGameSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerExitGameSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[10].Descriptor()
}

func (MsgPlayerExitGameSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[10]
}

func (x MsgPlayerExitGameSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerExitGameSync_ProtoId.Descriptor instead.
func (MsgPlayerExitGameSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10, 0}
}

type MsgPlayerBasicInfoReq_ProtoId int32

const (
	MsgPlayerBasicInfoReq_None MsgPlayerBasicInfoReq_ProtoId = 0
	MsgPlayerBasicInfoReq_Id   MsgPlayerBasicInfoReq_ProtoId = 120
)

// Enum value maps for MsgPlayerBasicInfoReq_ProtoId.
var (
	MsgPlayerBasicInfoReq_ProtoId_name = map[int32]string{
		0:   "None",
		120: "Id",
	}
	MsgPlayerBasicInfoReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   120,
	}
)

func (x MsgPlayerBasicInfoReq_ProtoId) Enum() *MsgPlayerBasicInfoReq_ProtoId {
	p := new(MsgPlayerBasicInfoReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerBasicInfoReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerBasicInfoReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[11].Descriptor()
}

func (MsgPlayerBasicInfoReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[11]
}

func (x MsgPlayerBasicInfoReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerBasicInfoReq_ProtoId.Descriptor instead.
func (MsgPlayerBasicInfoReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11, 0}
}

type MsgPlayerBasicInfoAck_ProtoId int32

const (
	MsgPlayerBasicInfoAck_None MsgPlayerBasicInfoAck_ProtoId = 0
	MsgPlayerBasicInfoAck_Id   MsgPlayerBasicInfoAck_ProtoId = 121
)

// Enum value maps for MsgPlayerBasicInfoAck_ProtoId.
var (
	MsgPlayerBasicInfoAck_ProtoId_name = map[int32]string{
		0:   "None",
		121: "Id",
	}
	MsgPlayerBasicInfoAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   121,
	}
)

func (x MsgPlayerBasicInfoAck_ProtoId) Enum() *MsgPlayerBasicInfoAck_ProtoId {
	p := new(MsgPlayerBasicInfoAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerBasicInfoAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerBasicInfoAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[12].Descriptor()
}

func (MsgPlayerBasicInfoAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[12]
}

func (x MsgPlayerBasicInfoAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerBasicInfoAck_ProtoId.Descriptor instead.
func (MsgPlayerBasicInfoAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12, 0}
}

type MsgPlayerTankMoveReq_ProtoId int32

const (
	MsgPlayerTankMoveReq_None MsgPlayerTankMoveReq_ProtoId = 0
	MsgPlayerTankMoveReq_Id   MsgPlayerTankMoveReq_ProtoId = 200
)

// Enum value maps for MsgPlayerTankMoveReq_ProtoId.
var (
	MsgPlayerTankMoveReq_ProtoId_name = map[int32]string{
		0:   "None",
		200: "Id",
	}
	MsgPlayerTankMoveReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   200,
	}
)

func (x MsgPlayerTankMoveReq_ProtoId) Enum() *MsgPlayerTankMoveReq_ProtoId {
	p := new(MsgPlayerTankMoveReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankMoveReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankMoveReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[13].Descriptor()
}

func (MsgPlayerTankMoveReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[13]
}

func (x MsgPlayerTankMoveReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankMoveReq_ProtoId.Descriptor instead.
func (MsgPlayerTankMoveReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13, 0}
}

type MsgPlayerTankMoveAck_ProtoId int32

const (
	MsgPlayerTankMoveAck_None MsgPlayerTankMoveAck_ProtoId = 0
	MsgPlayerTankMoveAck_Id   MsgPlayerTankMoveAck_ProtoId = 201
)

// Enum value maps for MsgPlayerTankMoveAck_ProtoId.
var (
	MsgPlayerTankMoveAck_ProtoId_name = map[int32]string{
		0:   "None",
		201: "Id",
	}
	MsgPlayerTankMoveAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   201,
	}
)

func (x MsgPlayerTankMoveAck_ProtoId) Enum() *MsgPlayerTankMoveAck_ProtoId {
	p := new(MsgPlayerTankMoveAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankMoveAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankMoveAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[14].Descriptor()
}

func (MsgPlayerTankMoveAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[14]
}

func (x MsgPlayerTankMoveAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankMoveAck_ProtoId.Descriptor instead.
func (MsgPlayerTankMoveAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14, 0}
}

type MsgPlayerTankMoveSync_ProtoId int32

const (
	MsgPlayerTankMoveSync_None MsgPlayerTankMoveSync_ProtoId = 0
	MsgPlayerTankMoveSync_Id   MsgPlayerTankMoveSync_ProtoId = 202
)

// Enum value maps for MsgPlayerTankMoveSync_ProtoId.
var (
	MsgPlayerTankMoveSync_ProtoId_name = map[int32]string{
		0:   "None",
		202: "Id",
	}
	MsgPlayerTankMoveSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   202,
	}
)

func (x MsgPlayerTankMoveSync_ProtoId) Enum() *MsgPlayerTankMoveSync_ProtoId {
	p := new(MsgPlayerTankMoveSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankMoveSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankMoveSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[15].Descriptor()
}

func (MsgPlayerTankMoveSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[15]
}

func (x MsgPlayerTankMoveSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankMoveSync_ProtoId.Descriptor instead.
func (MsgPlayerTankMoveSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15, 0}
}

type MsgPlayerTankStopMoveReq_ProtoId int32

const (
	MsgPlayerTankStopMoveReq_None MsgPlayerTankStopMoveReq_ProtoId = 0
	MsgPlayerTankStopMoveReq_Id   MsgPlayerTankStopMoveReq_ProtoId = 203
)

// Enum value maps for MsgPlayerTankStopMoveReq_ProtoId.
var (
	MsgPlayerTankStopMoveReq_ProtoId_name = map[int32]string{
		0:   "None",
		203: "Id",
	}
	MsgPlayerTankStopMoveReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   203,
	}
)

func (x MsgPlayerTankStopMoveReq_ProtoId) Enum() *MsgPlayerTankStopMoveReq_ProtoId {
	p := new(MsgPlayerTankStopMoveReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankStopMoveReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankStopMoveReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[16].Descriptor()
}

func (MsgPlayerTankStopMoveReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[16]
}

func (x MsgPlayerTankStopMoveReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankStopMoveReq_ProtoId.Descriptor instead.
func (MsgPlayerTankStopMoveReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16, 0}
}

type MsgPlayerTankStopMoveAck_ProtoId int32

const (
	MsgPlayerTankStopMoveAck_None MsgPlayerTankStopMoveAck_ProtoId = 0
	MsgPlayerTankStopMoveAck_Id   MsgPlayerTankStopMoveAck_ProtoId = 204
)

// Enum value maps for MsgPlayerTankStopMoveAck_ProtoId.
var (
	MsgPlayerTankStopMoveAck_ProtoId_name = map[int32]string{
		0:   "None",
		204: "Id",
	}
	MsgPlayerTankStopMoveAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   204,
	}
)

func (x MsgPlayerTankStopMoveAck_ProtoId) Enum() *MsgPlayerTankStopMoveAck_ProtoId {
	p := new(MsgPlayerTankStopMoveAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankStopMoveAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankStopMoveAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[17].Descriptor()
}

func (MsgPlayerTankStopMoveAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[17]
}

func (x MsgPlayerTankStopMoveAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankStopMoveAck_ProtoId.Descriptor instead.
func (MsgPlayerTankStopMoveAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17, 0}
}

type MsgPlayerTankStopMoveSync_ProtoId int32

const (
	MsgPlayerTankStopMoveSync_None MsgPlayerTankStopMoveSync_ProtoId = 0
	MsgPlayerTankStopMoveSync_Id   MsgPlayerTankStopMoveSync_ProtoId = 205
)

// Enum value maps for MsgPlayerTankStopMoveSync_ProtoId.
var (
	MsgPlayerTankStopMoveSync_ProtoId_name = map[int32]string{
		0:   "None",
		205: "Id",
	}
	MsgPlayerTankStopMoveSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   205,
	}
)

func (x MsgPlayerTankStopMoveSync_ProtoId) Enum() *MsgPlayerTankStopMoveSync_ProtoId {
	p := new(MsgPlayerTankStopMoveSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerTankStopMoveSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerTankStopMoveSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[18].Descriptor()
}

func (MsgPlayerTankStopMoveSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[18]
}

func (x MsgPlayerTankStopMoveSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerTankStopMoveSync_ProtoId.Descriptor instead.
func (MsgPlayerTankStopMoveSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18, 0}
}

type MsgPlayerChangeTankReq_ProtoId int32

const (
	MsgPlayerChangeTankReq_None MsgPlayerChangeTankReq_ProtoId = 0
	MsgPlayerChangeTankReq_Id   MsgPlayerChangeTankReq_ProtoId = 210
)

// Enum value maps for MsgPlayerChangeTankReq_ProtoId.
var (
	MsgPlayerChangeTankReq_ProtoId_name = map[int32]string{
		0:   "None",
		210: "Id",
	}
	MsgPlayerChangeTankReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   210,
	}
)

func (x MsgPlayerChangeTankReq_ProtoId) Enum() *MsgPlayerChangeTankReq_ProtoId {
	p := new(MsgPlayerChangeTankReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerChangeTankReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerChangeTankReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[19].Descriptor()
}

func (MsgPlayerChangeTankReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[19]
}

func (x MsgPlayerChangeTankReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerChangeTankReq_ProtoId.Descriptor instead.
func (MsgPlayerChangeTankReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19, 0}
}

type MsgPlayerChangeTankAck_ProtoId int32

const (
	MsgPlayerChangeTankAck_None MsgPlayerChangeTankAck_ProtoId = 0
	MsgPlayerChangeTankAck_Id   MsgPlayerChangeTankAck_ProtoId = 211
)

// Enum value maps for MsgPlayerChangeTankAck_ProtoId.
var (
	MsgPlayerChangeTankAck_ProtoId_name = map[int32]string{
		0:   "None",
		211: "Id",
	}
	MsgPlayerChangeTankAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   211,
	}
)

func (x MsgPlayerChangeTankAck_ProtoId) Enum() *MsgPlayerChangeTankAck_ProtoId {
	p := new(MsgPlayerChangeTankAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerChangeTankAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerChangeTankAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[20].Descriptor()
}

func (MsgPlayerChangeTankAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[20]
}

func (x MsgPlayerChangeTankAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerChangeTankAck_ProtoId.Descriptor instead.
func (MsgPlayerChangeTankAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{20, 0}
}

type MsgPlayerChangeTankSync_ProtoId int32

const (
	MsgPlayerChangeTankSync_None MsgPlayerChangeTankSync_ProtoId = 0
	MsgPlayerChangeTankSync_Id   MsgPlayerChangeTankSync_ProtoId = 212
)

// Enum value maps for MsgPlayerChangeTankSync_ProtoId.
var (
	MsgPlayerChangeTankSync_ProtoId_name = map[int32]string{
		0:   "None",
		212: "Id",
	}
	MsgPlayerChangeTankSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   212,
	}
)

func (x MsgPlayerChangeTankSync_ProtoId) Enum() *MsgPlayerChangeTankSync_ProtoId {
	p := new(MsgPlayerChangeTankSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerChangeTankSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerChangeTankSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[21].Descriptor()
}

func (MsgPlayerChangeTankSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[21]
}

func (x MsgPlayerChangeTankSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerChangeTankSync_ProtoId.Descriptor instead.
func (MsgPlayerChangeTankSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{21, 0}
}

type MsgPlayerRestoreTankReq_ProtoId int32

const (
	MsgPlayerRestoreTankReq_None MsgPlayerRestoreTankReq_ProtoId = 0
	MsgPlayerRestoreTankReq_Id   MsgPlayerRestoreTankReq_ProtoId = 213
)

// Enum value maps for MsgPlayerRestoreTankReq_ProtoId.
var (
	MsgPlayerRestoreTankReq_ProtoId_name = map[int32]string{
		0:   "None",
		213: "Id",
	}
	MsgPlayerRestoreTankReq_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   213,
	}
)

func (x MsgPlayerRestoreTankReq_ProtoId) Enum() *MsgPlayerRestoreTankReq_ProtoId {
	p := new(MsgPlayerRestoreTankReq_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerRestoreTankReq_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerRestoreTankReq_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[22].Descriptor()
}

func (MsgPlayerRestoreTankReq_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[22]
}

func (x MsgPlayerRestoreTankReq_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerRestoreTankReq_ProtoId.Descriptor instead.
func (MsgPlayerRestoreTankReq_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{22, 0}
}

type MsgPlayerRestoreTankAck_ProtoId int32

const (
	MsgPlayerRestoreTankAck_None MsgPlayerRestoreTankAck_ProtoId = 0
	MsgPlayerRestoreTankAck_Id   MsgPlayerRestoreTankAck_ProtoId = 214
)

// Enum value maps for MsgPlayerRestoreTankAck_ProtoId.
var (
	MsgPlayerRestoreTankAck_ProtoId_name = map[int32]string{
		0:   "None",
		214: "Id",
	}
	MsgPlayerRestoreTankAck_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   214,
	}
)

func (x MsgPlayerRestoreTankAck_ProtoId) Enum() *MsgPlayerRestoreTankAck_ProtoId {
	p := new(MsgPlayerRestoreTankAck_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerRestoreTankAck_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerRestoreTankAck_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[23].Descriptor()
}

func (MsgPlayerRestoreTankAck_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[23]
}

func (x MsgPlayerRestoreTankAck_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerRestoreTankAck_ProtoId.Descriptor instead.
func (MsgPlayerRestoreTankAck_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{23, 0}
}

type MsgPlayerRestoreTankSync_ProtoId int32

const (
	MsgPlayerRestoreTankSync_None MsgPlayerRestoreTankSync_ProtoId = 0
	MsgPlayerRestoreTankSync_Id   MsgPlayerRestoreTankSync_ProtoId = 215
)

// Enum value maps for MsgPlayerRestoreTankSync_ProtoId.
var (
	MsgPlayerRestoreTankSync_ProtoId_name = map[int32]string{
		0:   "None",
		215: "Id",
	}
	MsgPlayerRestoreTankSync_ProtoId_value = map[string]int32{
		"None": 0,
		"Id":   215,
	}
)

func (x MsgPlayerRestoreTankSync_ProtoId) Enum() *MsgPlayerRestoreTankSync_ProtoId {
	p := new(MsgPlayerRestoreTankSync_ProtoId)
	*p = x
	return p
}

func (x MsgPlayerRestoreTankSync_ProtoId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgPlayerRestoreTankSync_ProtoId) Descriptor() protoreflect.EnumDescriptor {
	return file_game_proto_enumTypes[24].Descriptor()
}

func (MsgPlayerRestoreTankSync_ProtoId) Type() protoreflect.EnumType {
	return &file_game_proto_enumTypes[24]
}

func (x MsgPlayerRestoreTankSync_ProtoId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgPlayerRestoreTankSync_ProtoId.Descriptor instead.
func (MsgPlayerRestoreTankSync_ProtoId) EnumDescriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{24, 0}
}

// 登录
type MsgAccountLoginGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account     string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Password    string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	AccessToken string `protobuf:"bytes,3,opt,name=AccessToken,proto3" json:"AccessToken,omitempty"`
}

func (x *MsgAccountLoginGameReq) Reset() {
	*x = MsgAccountLoginGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAccountLoginGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAccountLoginGameReq) ProtoMessage() {}

func (x *MsgAccountLoginGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAccountLoginGameReq.ProtoReflect.Descriptor instead.
func (*MsgAccountLoginGameReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *MsgAccountLoginGameReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgAccountLoginGameReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *MsgAccountLoginGameReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 登录返回
type MsgAccountLoginGameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
	Result       uint32 `protobuf:"varint,3,opt,name=Result,proto3" json:"Result,omitempty"`
}

func (x *MsgAccountLoginGameAck) Reset() {
	*x = MsgAccountLoginGameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgAccountLoginGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgAccountLoginGameAck) ProtoMessage() {}

func (x *MsgAccountLoginGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgAccountLoginGameAck.ProtoReflect.Descriptor instead.
func (*MsgAccountLoginGameAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *MsgAccountLoginGameAck) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgAccountLoginGameAck) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *MsgAccountLoginGameAck) GetResult() uint32 {
	if x != nil {
		return x.Result
	}
	return 0
}

// 时间同步请求
type MsgTimeSyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientTime []byte `protobuf:"bytes,1,opt,name=ClientTime,proto3" json:"ClientTime,omitempty"`
}

func (x *MsgTimeSyncReq) Reset() {
	*x = MsgTimeSyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTimeSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTimeSyncReq) ProtoMessage() {}

func (x *MsgTimeSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTimeSyncReq.ProtoReflect.Descriptor instead.
func (*MsgTimeSyncReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *MsgTimeSyncReq) GetClientTime() []byte {
	if x != nil {
		return x.ClientTime
	}
	return nil
}

// 时间同步返回
type MsgTimeSyncAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime []byte `protobuf:"bytes,2,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"`
}

func (x *MsgTimeSyncAck) Reset() {
	*x = MsgTimeSyncAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgTimeSyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTimeSyncAck) ProtoMessage() {}

func (x *MsgTimeSyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTimeSyncAck.ProtoReflect.Descriptor instead.
func (*MsgTimeSyncAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *MsgTimeSyncAck) GetServerTime() []byte {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// 进入游戏请求
type MsgPlayerEnterGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      string `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	SessionToken string `protobuf:"bytes,2,opt,name=SessionToken,proto3" json:"SessionToken,omitempty"`
}

func (x *MsgPlayerEnterGameReq) Reset() {
	*x = MsgPlayerEnterGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerEnterGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerEnterGameReq) ProtoMessage() {}

func (x *MsgPlayerEnterGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerEnterGameReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerEnterGameReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *MsgPlayerEnterGameReq) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *MsgPlayerEnterGameReq) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

// 进入游戏返回
type MsgPlayerEnterGameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SelfTankInfo            *PlayerAccountTankInfo   `protobuf:"bytes,1,opt,name=SelfTankInfo,proto3" json:"SelfTankInfo,omitempty"`
	OtherPlayerTankInfoList []*PlayerAccountTankInfo `protobuf:"bytes,2,rep,name=OtherPlayerTankInfoList,proto3" json:"OtherPlayerTankInfoList,omitempty"`
}

func (x *MsgPlayerEnterGameAck) Reset() {
	*x = MsgPlayerEnterGameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerEnterGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerEnterGameAck) ProtoMessage() {}

func (x *MsgPlayerEnterGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerEnterGameAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerEnterGameAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *MsgPlayerEnterGameAck) GetSelfTankInfo() *PlayerAccountTankInfo {
	if x != nil {
		return x.SelfTankInfo
	}
	return nil
}

func (x *MsgPlayerEnterGameAck) GetOtherPlayerTankInfoList() []*PlayerAccountTankInfo {
	if x != nil {
		return x.OtherPlayerTankInfoList
	}
	return nil
}

// 进入游戏结束通知
type MsgPlayerEnterGameFinishNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerTime []byte `protobuf:"bytes,1,opt,name=ServerTime,proto3" json:"ServerTime,omitempty"` // 服务器时间
}

func (x *MsgPlayerEnterGameFinishNtf) Reset() {
	*x = MsgPlayerEnterGameFinishNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerEnterGameFinishNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerEnterGameFinishNtf) ProtoMessage() {}

func (x *MsgPlayerEnterGameFinishNtf) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerEnterGameFinishNtf.ProtoReflect.Descriptor instead.
func (*MsgPlayerEnterGameFinishNtf) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *MsgPlayerEnterGameFinishNtf) GetServerTime() []byte {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// 玩家进入游戏同步
type MsgPlayerEnterGameSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TankInfo *PlayerAccountTankInfo `protobuf:"bytes,1,opt,name=TankInfo,proto3" json:"TankInfo,omitempty"`
}

func (x *MsgPlayerEnterGameSync) Reset() {
	*x = MsgPlayerEnterGameSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerEnterGameSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerEnterGameSync) ProtoMessage() {}

func (x *MsgPlayerEnterGameSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerEnterGameSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerEnterGameSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *MsgPlayerEnterGameSync) GetTankInfo() *PlayerAccountTankInfo {
	if x != nil {
		return x.TankInfo
	}
	return nil
}

// 退出游戏请求
type MsgPlayerExitGameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerExitGameReq) Reset() {
	*x = MsgPlayerExitGameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerExitGameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerExitGameReq) ProtoMessage() {}

func (x *MsgPlayerExitGameReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerExitGameReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerExitGameReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

// 退出游戏返回
type MsgPlayerExitGameAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerExitGameAck) Reset() {
	*x = MsgPlayerExitGameAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerExitGameAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerExitGameAck) ProtoMessage() {}

func (x *MsgPlayerExitGameAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerExitGameAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerExitGameAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

// 玩家退出游戏同步
type MsgPlayerExitGameSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *MsgPlayerExitGameSync) Reset() {
	*x = MsgPlayerExitGameSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerExitGameSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerExitGameSync) ProtoMessage() {}

func (x *MsgPlayerExitGameSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerExitGameSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerExitGameSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *MsgPlayerExitGameSync) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 玩家基本信息请求
type MsgPlayerBasicInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerBasicInfoReq) Reset() {
	*x = MsgPlayerBasicInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerBasicInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerBasicInfoReq) ProtoMessage() {}

func (x *MsgPlayerBasicInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerBasicInfoReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerBasicInfoReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{11}
}

// 玩家基本信息返回
type MsgPlayerBasicInfoAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerBasicInfoAck) Reset() {
	*x = MsgPlayerBasicInfoAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerBasicInfoAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerBasicInfoAck) ProtoMessage() {}

func (x *MsgPlayerBasicInfoAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerBasicInfoAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerBasicInfoAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{12}
}

// 坦克移动请求
type MsgPlayerTankMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MoveInfo *TankMoveInfo `protobuf:"bytes,1,opt,name=MoveInfo,proto3" json:"MoveInfo,omitempty"`
}

func (x *MsgPlayerTankMoveReq) Reset() {
	*x = MsgPlayerTankMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankMoveReq) ProtoMessage() {}

func (x *MsgPlayerTankMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankMoveReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankMoveReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{13}
}

func (x *MsgPlayerTankMoveReq) GetMoveInfo() *TankMoveInfo {
	if x != nil {
		return x.MoveInfo
	}
	return nil
}

// 坦克移动返回
type MsgPlayerTankMoveAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *MsgPlayerTankMoveAck) Reset() {
	*x = MsgPlayerTankMoveAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankMoveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankMoveAck) ProtoMessage() {}

func (x *MsgPlayerTankMoveAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankMoveAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankMoveAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{14}
}

func (x *MsgPlayerTankMoveAck) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 坦克移动同步
type MsgPlayerTankMoveSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64        `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	MoveInfo *TankMoveInfo `protobuf:"bytes,2,opt,name=MoveInfo,proto3" json:"MoveInfo,omitempty"`
}

func (x *MsgPlayerTankMoveSync) Reset() {
	*x = MsgPlayerTankMoveSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankMoveSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankMoveSync) ProtoMessage() {}

func (x *MsgPlayerTankMoveSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankMoveSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankMoveSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{15}
}

func (x *MsgPlayerTankMoveSync) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MsgPlayerTankMoveSync) GetMoveInfo() *TankMoveInfo {
	if x != nil {
		return x.MoveInfo
	}
	return nil
}

// 坦克停止移动请求
type MsgPlayerTankStopMoveReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerTankStopMoveReq) Reset() {
	*x = MsgPlayerTankStopMoveReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankStopMoveReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankStopMoveReq) ProtoMessage() {}

func (x *MsgPlayerTankStopMoveReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankStopMoveReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankStopMoveReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{16}
}

// 坦克停止移动返回
type MsgPlayerTankStopMoveAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerTankStopMoveAck) Reset() {
	*x = MsgPlayerTankStopMoveAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankStopMoveAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankStopMoveAck) ProtoMessage() {}

func (x *MsgPlayerTankStopMoveAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankStopMoveAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankStopMoveAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{17}
}

// 坦克停止移动同步
type MsgPlayerTankStopMoveSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
}

func (x *MsgPlayerTankStopMoveSync) Reset() {
	*x = MsgPlayerTankStopMoveSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerTankStopMoveSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerTankStopMoveSync) ProtoMessage() {}

func (x *MsgPlayerTankStopMoveSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerTankStopMoveSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerTankStopMoveSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{18}
}

func (x *MsgPlayerTankStopMoveSync) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

// 改变坦克请求
type MsgPlayerChangeTankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TankId int32 `protobuf:"varint,1,opt,name=TankId,proto3" json:"TankId,omitempty"` // 坦克id
}

func (x *MsgPlayerChangeTankReq) Reset() {
	*x = MsgPlayerChangeTankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerChangeTankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerChangeTankReq) ProtoMessage() {}

func (x *MsgPlayerChangeTankReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerChangeTankReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerChangeTankReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{19}
}

func (x *MsgPlayerChangeTankReq) GetTankId() int32 {
	if x != nil {
		return x.TankId
	}
	return 0
}

// 改变坦克回复
type MsgPlayerChangeTankAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangedTankInfo *TankInfo `protobuf:"bytes,1,opt,name=ChangedTankInfo,proto3" json:"ChangedTankInfo,omitempty"`
}

func (x *MsgPlayerChangeTankAck) Reset() {
	*x = MsgPlayerChangeTankAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerChangeTankAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerChangeTankAck) ProtoMessage() {}

func (x *MsgPlayerChangeTankAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerChangeTankAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerChangeTankAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{20}
}

func (x *MsgPlayerChangeTankAck) GetChangedTankInfo() *TankInfo {
	if x != nil {
		return x.ChangedTankInfo
	}
	return nil
}

// 改变坦克同步
type MsgPlayerChangeTankSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChangedTankInfo *PlayerTankInfo `protobuf:"bytes,1,opt,name=ChangedTankInfo,proto3" json:"ChangedTankInfo,omitempty"`
}

func (x *MsgPlayerChangeTankSync) Reset() {
	*x = MsgPlayerChangeTankSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerChangeTankSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerChangeTankSync) ProtoMessage() {}

func (x *MsgPlayerChangeTankSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerChangeTankSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerChangeTankSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{21}
}

func (x *MsgPlayerChangeTankSync) GetChangedTankInfo() *PlayerTankInfo {
	if x != nil {
		return x.ChangedTankInfo
	}
	return nil
}

// 恢复坦克请求
type MsgPlayerRestoreTankReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *MsgPlayerRestoreTankReq) Reset() {
	*x = MsgPlayerRestoreTankReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerRestoreTankReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerRestoreTankReq) ProtoMessage() {}

func (x *MsgPlayerRestoreTankReq) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerRestoreTankReq.ProtoReflect.Descriptor instead.
func (*MsgPlayerRestoreTankReq) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{22}
}

// 恢复坦克回应
type MsgPlayerRestoreTankAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TankId int32 `protobuf:"varint,1,opt,name=TankId,proto3" json:"TankId,omitempty"`
}

func (x *MsgPlayerRestoreTankAck) Reset() {
	*x = MsgPlayerRestoreTankAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerRestoreTankAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerRestoreTankAck) ProtoMessage() {}

func (x *MsgPlayerRestoreTankAck) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerRestoreTankAck.ProtoReflect.Descriptor instead.
func (*MsgPlayerRestoreTankAck) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{23}
}

func (x *MsgPlayerRestoreTankAck) GetTankId() int32 {
	if x != nil {
		return x.TankId
	}
	return 0
}

// 恢复坦克同步
type MsgPlayerRestoreTankSync struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	TankId   int32  `protobuf:"varint,2,opt,name=TankId,proto3" json:"TankId,omitempty"`
}

func (x *MsgPlayerRestoreTankSync) Reset() {
	*x = MsgPlayerRestoreTankSync{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgPlayerRestoreTankSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPlayerRestoreTankSync) ProtoMessage() {}

func (x *MsgPlayerRestoreTankSync) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPlayerRestoreTankSync.ProtoReflect.Descriptor instead.
func (*MsgPlayerRestoreTankSync) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{24}
}

func (x *MsgPlayerRestoreTankSync) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MsgPlayerRestoreTankSync) GetTankId() int32 {
	if x != nil {
		return x.TankId
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x67, 0x61,
	0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x49, 0x64, 0x10, 0x01, 0x22, 0x8b, 0x01, 0x0a, 0x16, 0x4d, 0x73, 0x67, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02,
	0x49, 0x64, 0x10, 0x02, 0x22, 0x4d, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49,
	0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49,
	0x64, 0x10, 0x0a, 0x22, 0x4d, 0x0a, 0x0e, 0x4d, 0x73, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x79,
	0x6e, 0x63, 0x41, 0x63, 0x6b, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64,
	0x10, 0x0b, 0x22, 0x72, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x49, 0x64, 0x10, 0x64, 0x22, 0xd8, 0x01, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x6b,
	0x12, 0x45, 0x0a, 0x0c, 0x53, 0x65, 0x6c, 0x66, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x53, 0x65, 0x6c, 0x66, 0x54,
	0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x5b, 0x0a, 0x17, 0x4f, 0x74, 0x68, 0x65, 0x72,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x17, 0x4f, 0x74, 0x68,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12,
	0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10,
	0x65, 0x22, 0x5a, 0x0a, 0x1b, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e,
	0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x4e, 0x74, 0x66,
	0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x66, 0x22, 0x74, 0x0a,
	0x16, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x3d, 0x0a, 0x08, 0x54, 0x61, 0x6e, 0x6b, 0x49,
	0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x54, 0x61,
	0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49,
	0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49,
	0x64, 0x10, 0x67, 0x22, 0x33, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x45, 0x78, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x22, 0x1b, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x6e, 0x22, 0x33, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x41, 0x63, 0x6b,
	0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x6f, 0x22, 0x50, 0x0a,
	0x15, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x78, 0x69, 0x74, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a,
	0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x70, 0x22,
	0x34, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x42, 0x61, 0x73, 0x69,
	0x63, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x22, 0x1b, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x06, 0x0a,
	0x02, 0x49, 0x64, 0x10, 0x78, 0x22, 0x34, 0x0a, 0x15, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x42, 0x61, 0x73, 0x69, 0x63, 0x49, 0x6e, 0x66, 0x6f, 0x41, 0x63, 0x6b, 0x22, 0x1b,
	0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e,
	0x65, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x49, 0x64, 0x10, 0x79, 0x22, 0x6a, 0x0a, 0x14, 0x4d,
	0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x34, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x54, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x08, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x02, 0x49, 0x64, 0x10, 0xc8, 0x01, 0x22, 0x50, 0x0a, 0x14, 0x4d, 0x73, 0x67, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x6b, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x1c, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00,
	0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xc9, 0x01, 0x22, 0x87, 0x01, 0x0a, 0x15, 0x4d, 0x73,
	0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x34, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x61, 0x6e, 0x6b, 0x4d, 0x6f, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x4d, 0x6f, 0x76,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64,
	0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64,
	0x10, 0xca, 0x01, 0x22, 0x38, 0x0a, 0x18, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x54, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x65, 0x71, 0x22,
	0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xcb, 0x01, 0x22, 0x38, 0x0a,
	0x18, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x53, 0x74,
	0x6f, 0x70, 0x4d, 0x6f, 0x76, 0x65, 0x41, 0x63, 0x6b, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07,
	0x0a, 0x02, 0x49, 0x64, 0x10, 0xcc, 0x01, 0x22, 0x55, 0x0a, 0x19, 0x4d, 0x73, 0x67, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x54, 0x61, 0x6e, 0x6b, 0x53, 0x74, 0x6f, 0x70, 0x4d, 0x6f, 0x76, 0x65,
	0x53, 0x79, 0x6e, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64,
	0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xcd, 0x01, 0x22, 0x4e,
	0x0a, 0x16, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x6e, 0x6b,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x64,
	0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xd2, 0x01, 0x22, 0x76,
	0x0a, 0x16, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x64, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64,
	0x54, 0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a,
	0x02, 0x49, 0x64, 0x10, 0xd3, 0x01, 0x22, 0x7d, 0x0a, 0x17, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x54, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x6e,
	0x63, 0x12, 0x44, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54, 0x61, 0x6e, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x61,
	0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x54,
	0x61, 0x6e, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02,
	0x49, 0x64, 0x10, 0xd4, 0x01, 0x22, 0x37, 0x0a, 0x17, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x54, 0x61, 0x6e, 0x6b, 0x52, 0x65, 0x71,
	0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e,
	0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xd5, 0x01, 0x22, 0x4f,
	0x0a, 0x17, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x54, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x6e,
	0x6b, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x61, 0x6e, 0x6b, 0x49,
	0x64, 0x22, 0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04,
	0x4e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xd6, 0x01, 0x22,
	0x6c, 0x0a, 0x18, 0x4d, 0x73, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x54, 0x61, 0x6e, 0x6b, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x50,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x6e, 0x6b, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x61, 0x6e, 0x6b, 0x49, 0x64, 0x22,
	0x1c, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f,
	0x6e, 0x65, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x02, 0x49, 0x64, 0x10, 0xd7, 0x01, 0x42, 0x0f, 0x5a,
	0x0d, 0x2e, 0x2e, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_enumTypes = make([]protoimpl.EnumInfo, 25)
var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_game_proto_goTypes = []interface{}{
	(MsgAccountLoginGameReq_ProtoId)(0),      // 0: game_proto.MsgAccountLoginGameReq.ProtoId
	(MsgAccountLoginGameAck_ProtoId)(0),      // 1: game_proto.MsgAccountLoginGameAck.ProtoId
	(MsgTimeSyncReq_ProtoId)(0),              // 2: game_proto.MsgTimeSyncReq.ProtoId
	(MsgTimeSyncAck_ProtoId)(0),              // 3: game_proto.MsgTimeSyncAck.ProtoId
	(MsgPlayerEnterGameReq_ProtoId)(0),       // 4: game_proto.MsgPlayerEnterGameReq.ProtoId
	(MsgPlayerEnterGameAck_ProtoId)(0),       // 5: game_proto.MsgPlayerEnterGameAck.ProtoId
	(MsgPlayerEnterGameFinishNtf_ProtoId)(0), // 6: game_proto.MsgPlayerEnterGameFinishNtf.ProtoId
	(MsgPlayerEnterGameSync_ProtoId)(0),      // 7: game_proto.MsgPlayerEnterGameSync.ProtoId
	(MsgPlayerExitGameReq_ProtoId)(0),        // 8: game_proto.MsgPlayerExitGameReq.ProtoId
	(MsgPlayerExitGameAck_ProtoId)(0),        // 9: game_proto.MsgPlayerExitGameAck.ProtoId
	(MsgPlayerExitGameSync_ProtoId)(0),       // 10: game_proto.MsgPlayerExitGameSync.ProtoId
	(MsgPlayerBasicInfoReq_ProtoId)(0),       // 11: game_proto.MsgPlayerBasicInfoReq.ProtoId
	(MsgPlayerBasicInfoAck_ProtoId)(0),       // 12: game_proto.MsgPlayerBasicInfoAck.ProtoId
	(MsgPlayerTankMoveReq_ProtoId)(0),        // 13: game_proto.MsgPlayerTankMoveReq.ProtoId
	(MsgPlayerTankMoveAck_ProtoId)(0),        // 14: game_proto.MsgPlayerTankMoveAck.ProtoId
	(MsgPlayerTankMoveSync_ProtoId)(0),       // 15: game_proto.MsgPlayerTankMoveSync.ProtoId
	(MsgPlayerTankStopMoveReq_ProtoId)(0),    // 16: game_proto.MsgPlayerTankStopMoveReq.ProtoId
	(MsgPlayerTankStopMoveAck_ProtoId)(0),    // 17: game_proto.MsgPlayerTankStopMoveAck.ProtoId
	(MsgPlayerTankStopMoveSync_ProtoId)(0),   // 18: game_proto.MsgPlayerTankStopMoveSync.ProtoId
	(MsgPlayerChangeTankReq_ProtoId)(0),      // 19: game_proto.MsgPlayerChangeTankReq.ProtoId
	(MsgPlayerChangeTankAck_ProtoId)(0),      // 20: game_proto.MsgPlayerChangeTankAck.ProtoId
	(MsgPlayerChangeTankSync_ProtoId)(0),     // 21: game_proto.MsgPlayerChangeTankSync.ProtoId
	(MsgPlayerRestoreTankReq_ProtoId)(0),     // 22: game_proto.MsgPlayerRestoreTankReq.ProtoId
	(MsgPlayerRestoreTankAck_ProtoId)(0),     // 23: game_proto.MsgPlayerRestoreTankAck.ProtoId
	(MsgPlayerRestoreTankSync_ProtoId)(0),    // 24: game_proto.MsgPlayerRestoreTankSync.ProtoId
	(*MsgAccountLoginGameReq)(nil),           // 25: game_proto.MsgAccountLoginGameReq
	(*MsgAccountLoginGameAck)(nil),           // 26: game_proto.MsgAccountLoginGameAck
	(*MsgTimeSyncReq)(nil),                   // 27: game_proto.MsgTimeSyncReq
	(*MsgTimeSyncAck)(nil),                   // 28: game_proto.MsgTimeSyncAck
	(*MsgPlayerEnterGameReq)(nil),            // 29: game_proto.MsgPlayerEnterGameReq
	(*MsgPlayerEnterGameAck)(nil),            // 30: game_proto.MsgPlayerEnterGameAck
	(*MsgPlayerEnterGameFinishNtf)(nil),      // 31: game_proto.MsgPlayerEnterGameFinishNtf
	(*MsgPlayerEnterGameSync)(nil),           // 32: game_proto.MsgPlayerEnterGameSync
	(*MsgPlayerExitGameReq)(nil),             // 33: game_proto.MsgPlayerExitGameReq
	(*MsgPlayerExitGameAck)(nil),             // 34: game_proto.MsgPlayerExitGameAck
	(*MsgPlayerExitGameSync)(nil),            // 35: game_proto.MsgPlayerExitGameSync
	(*MsgPlayerBasicInfoReq)(nil),            // 36: game_proto.MsgPlayerBasicInfoReq
	(*MsgPlayerBasicInfoAck)(nil),            // 37: game_proto.MsgPlayerBasicInfoAck
	(*MsgPlayerTankMoveReq)(nil),             // 38: game_proto.MsgPlayerTankMoveReq
	(*MsgPlayerTankMoveAck)(nil),             // 39: game_proto.MsgPlayerTankMoveAck
	(*MsgPlayerTankMoveSync)(nil),            // 40: game_proto.MsgPlayerTankMoveSync
	(*MsgPlayerTankStopMoveReq)(nil),         // 41: game_proto.MsgPlayerTankStopMoveReq
	(*MsgPlayerTankStopMoveAck)(nil),         // 42: game_proto.MsgPlayerTankStopMoveAck
	(*MsgPlayerTankStopMoveSync)(nil),        // 43: game_proto.MsgPlayerTankStopMoveSync
	(*MsgPlayerChangeTankReq)(nil),           // 44: game_proto.MsgPlayerChangeTankReq
	(*MsgPlayerChangeTankAck)(nil),           // 45: game_proto.MsgPlayerChangeTankAck
	(*MsgPlayerChangeTankSync)(nil),          // 46: game_proto.MsgPlayerChangeTankSync
	(*MsgPlayerRestoreTankReq)(nil),          // 47: game_proto.MsgPlayerRestoreTankReq
	(*MsgPlayerRestoreTankAck)(nil),          // 48: game_proto.MsgPlayerRestoreTankAck
	(*MsgPlayerRestoreTankSync)(nil),         // 49: game_proto.MsgPlayerRestoreTankSync
	(*PlayerAccountTankInfo)(nil),            // 50: game_proto.PlayerAccountTankInfo
	(*TankMoveInfo)(nil),                     // 51: game_proto.TankMoveInfo
	(*TankInfo)(nil),                         // 52: game_proto.TankInfo
	(*PlayerTankInfo)(nil),                   // 53: game_proto.PlayerTankInfo
}
var file_game_proto_depIdxs = []int32{
	50, // 0: game_proto.MsgPlayerEnterGameAck.SelfTankInfo:type_name -> game_proto.PlayerAccountTankInfo
	50, // 1: game_proto.MsgPlayerEnterGameAck.OtherPlayerTankInfoList:type_name -> game_proto.PlayerAccountTankInfo
	50, // 2: game_proto.MsgPlayerEnterGameSync.TankInfo:type_name -> game_proto.PlayerAccountTankInfo
	51, // 3: game_proto.MsgPlayerTankMoveReq.MoveInfo:type_name -> game_proto.TankMoveInfo
	51, // 4: game_proto.MsgPlayerTankMoveSync.MoveInfo:type_name -> game_proto.TankMoveInfo
	52, // 5: game_proto.MsgPlayerChangeTankAck.ChangedTankInfo:type_name -> game_proto.TankInfo
	53, // 6: game_proto.MsgPlayerChangeTankSync.ChangedTankInfo:type_name -> game_proto.PlayerTankInfo
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAccountLoginGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgAccountLoginGameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTimeSyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgTimeSyncAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerEnterGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerEnterGameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerEnterGameFinishNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerEnterGameSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerExitGameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerExitGameAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerExitGameSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerBasicInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerBasicInfoAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankMoveAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankMoveSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankStopMoveReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankStopMoveAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerTankStopMoveSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerChangeTankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerChangeTankAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerChangeTankSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerRestoreTankReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerRestoreTankAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgPlayerRestoreTankSync); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      25,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		EnumInfos:         file_game_proto_enumTypes,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
